<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Content' => 'Inhalt',
    'Create New Entry' => 'Neue Eintrag erstellen',
    'Create New Section' => 'Neue Sektion erstellen',
    'Create Section' => 'Sektion erstellen',
    'Delete Entry' => 'Eintrag löschen',
    'Edit Entry' => 'Eintrag bearbeiten',
    'Entries' => 'Einträge',
    'Entry' => 'Eintrag',
    'Meta description' => 'Meta Beschreibung',
    'New Entry' => 'Neue Eintrag',
    'New Section' => 'Neue Sektion',
    'Order' => 'Reihenfolge',
    'Sections' => 'Sektionen',
    'The entry was created.' => 'Der Eintrag wurde erstellt.',
    'The entry was deleted.' => 'Der Eintrag wurde gelöscht.',
    'The entry was updated.' => 'Der Eintrag wurde aktualisiert.',
    'The section was created.' => 'Die Sektion wurde erstellt.',
    'The section was deleted.' => 'Die Sektion wurde gelöscht.',
    'The section was updated.' => 'Die Sektion wurde aktualisiert.',
    'Title' => 'Titel',
    'Update Section' => 'Sektion aktualisiern',
    'Url' => '',
    'View All Entries' => 'Alle Einträge anzeigen',
    'View All Sections' => 'Alle Sektionen anzeigen',
    '[ No title ]' => '[ Kein Titel ]',
];
