<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Hinzugefügt',
    'All devices' => 'Alle Geräte',
    'Alt text' => 'Alt text',
    'Are you sure you want to remove this asset?' => 'Sind sie sicher, dass sie dieses Asset löschen wollen?',
    'Assets' => 'Alt text',
    'Categories' => 'Kategorien',
    'Category' => 'Kategorie',
    'Content' => 'Inhalt',
    'Create New Category' => 'Neue Kategorie erstellen',
    'Create New Entry' => 'Neuen Eintrag erstellen',
    'Create New Section' => 'Neue Sektion erstellen',
    'Delete Category' => 'Kategorie löschen',
    'Delete Entry' => 'Eintrag löschen',
    'Delete Section' => 'Sektion löschen',
    'Desktop' => '',
    'Duplicate' => 'Duplizieren',
    'Edit Asset' => 'Asset bearbeiten',
    'Edit Category' => 'Kategorie bearbeiten',
    'Edit Entry' => 'Eintrag bearbeiten',
    'Edit Section' => 'Sektion aktualisiern',
    'Entries' => 'Einträge',
    'Entry' => 'Eintrag',
    'Library' => 'Dateien',
    'Link' => 'Link',
    'Meta description' => 'Meta Beschreibung',
    'Meta title' => 'Meta Titel',
    'Mobile' => 'Handy',
    'Name' => 'Name',
    'New Category' => 'Neue Kategorie',
    'New Entry' => 'Neuen Eintrag',
    'New Section' => 'Neue Sektion',
    'Notice: Removing an asset will not delete the actual file.' => 'Bitte beachten Sie, dass die Löschung eines Assets nicht die dazugehörige Datei löscht.',
    'Operations' => 'Operationen',
    'Permanently delete related files' => 'Unwiderruflich alle dazugehörige Dateien löschen',
    'Published' => 'Veröffentlichung',
    'Remove' => 'Entfernen',
    'Remove Asset' => 'Asset entfernen',
    'Sections' => 'Sektionen',
    'Subcategories' => 'Subkategorien',
    'The asset was added.' => 'Das Asset wurde hinzugefügt.',
    'The asset was created.' => 'Das Asset wurde erstellt.',
    'The asset was deleted.' => 'Das Asset wurde gelöscht.',
    'The asset was updated.' => 'Das Asset wurde aktualisiert.',
    'The category was created.' => 'Die Kategorie wurde erstellt.',
    'The category was deleted.' => 'Die Kategorie wurde gelöscht.',
    'The category was updated.' => 'Die Kategorie wurde aktualisiert.',
    'The entry was created.' => 'Der Eintrag wurde erstellt.',
    'The entry was deleted.' => 'Der Eintrag wurde gelöscht.',
    'The entry was duplicated.' => 'Der Eintrag wurde dupliziert.',
    'The entry was updated.' => 'Der Eintrag wurde aktualisiert.',
    'The section was created.' => 'Die Sektion wurde erstellt.',
    'The section was deleted.' => 'Die Sektion wurde gelöscht.',
    'The section was duplicated.' => 'Die Sektion wurde dupliziert.',
    'The section was updated.' => 'Die Sektion wurde aktualisiert.',
    'Title' => 'Titel',
    'Types' => 'Typen',
    'Upload' => 'Upload',
    'Url' => 'Url',
    'View All Entries' => 'Alle Einträge anzeigen',
    'View Entry' => 'Eintrag anzeigen',
    'View Section' => 'Sektion anzeigen',
    'Warning: Deleting this category cannot be undone. All related sections will also be unrecoverably deleted. All subcategories will also be unrecoverably deleted. Please be certain!' => 'Warnung: Das Löschen dieser Kategorie kann nicht rückgängig gemacht werden. Alle Subkategorien werden ebenfalls endgültig gelöscht. Bitte lassen Sie Vorsicht walten!',
    'Warning: Deleting this entry cannot be undone. All related sections will also be unrecoverably deleted. Please be certain!' => 'Warnung: Das Löschen dieses Eintrags kann nicht rückgängig gemacht werden. Alle Sektionen werden ebenfalls endgültig gelöscht. Bitte lassen Sie Vorsicht walten!',
    'Warning: Deleting this file cannot be undone. All related assets will also be unrecoverably deleted. Please be certain!' => 'Warnung: Das Löschen dieser Datei kann nicht rückgängig gemacht werden. Alle dazugehörigen Assets werden ebenfalls endgültig gelöscht. Bitte lassen Sie Vorsicht walten!',
    '[ No title ]' => '[ Kein Titel ]',
];
