<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All devices' => 'Alle Geräte',
    'Alt text' => '',
    'Are you sure you want to remove this asset?' => 'Sind sie sicher, dass sie dieses Asset löschen wollen?',
    'Assets' => '',
    'Content' => 'Inhalt',
    'Create New Entry' => 'Neuen Eintrag erstellen',
    'Create New Section' => 'Neue Sektion erstellen',
    'Create Section' => 'Sektion erstellen',
    'Delete Entry' => 'Eintrag löschen',
    'Desktop' => '',
    'Edit Asset' => 'Asset bearbeiten',
    'Edit Entry' => 'Eintrag bearbeiten',
    'Entries' => 'Einträge',
    'Entry' => 'Eintrag',
    'Library' => 'Dateien',
    'Link' => '',
    'Meta description' => 'Meta Beschreibung',
    'Meta title' => 'Meta Titel',
    'Mobile' => '',
    'New Entry' => 'Neuen Eintrag',
    'New Section' => 'Neue Sektion',
    'Notice: Removing an asset will not delete the actual file.' => 'Bitte beachten Sie, dass die Löschung eines Assets nicht die dazugehörige Datei löscht.',
    'Permanently delete related files' => 'Unwiderruflich alle dazugehörige Dateien löschen',
    'Published' => 'Veröffentlichung',
    'Remove' => 'Entfernen',
    'Remove Asset' => 'Asset entfernen',
    'Sections' => 'Sektionen',
    'The asset was added.' => 'Das Asset wurde hinzugefügt.',
    'The asset was created.' => 'Das Asset wurde erstellt.',
    'The asset was deleted.' => 'Das Asset wurde gelöscht.',
    'The asset was updated.' => 'Das Asset wurde aktualisiert.',
    'The entry was created.' => 'Der Eintrag wurde erstellt.',
    'The entry was deleted.' => 'Der Eintrag wurde gelöscht.',
    'The entry was updated.' => 'Der Eintrag wurde aktualisiert.',
    'The section was created.' => 'Die Sektion wurde erstellt.',
    'The section was deleted.' => 'Die Sektion wurde gelöscht.',
    'The section was updated.' => 'Die Sektion wurde aktualisiert.',
    'Title' => 'Titel',
    'Types' => '',
    'Update Section' => 'Sektion aktualisiern',
    'Upload' => '',
    'Url' => '',
    'View All Entries' => 'Alle Einträge anzeigen',
    'View All Sections' => 'Alle Sektionen anzeigen',
    'Warning: Deleting this entry cannot be undone. All related sections will also be unrecoverably deleted. Please be certain!' => '',
    'Warning: Deleting this file cannot be undone. All related assets will also be unrecoverably deleted. Please be certain!' => '',
    '[ No title ]' => '[ Kein Titel ]',
];
