<?php

declare(strict_types=1);

namespace Hirtz\Cms\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000400CmsBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            CREATE TABLE `entry` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `parent_status` tinyint(3) NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `tenant_id` int(11) unsigned NOT NULL,
              `parent_id` int(11) unsigned DEFAULT NULL,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`path`)),
              `name` varchar(255) NOT NULL,
              `title` varchar(255) DEFAULT NULL,
              `description` varchar(255) DEFAULT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `publish_date` datetime NOT NULL,
              `menu_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`menu_ids`)),
              `category_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`category_ids`)),
              `entry_count` int(11) unsigned NOT NULL DEFAULT 0,
              `section_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `asset_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              KEY `entry_updated_by_ibfk` (`updated_by_user_id`),
              KEY `entry_parent_id` (`parent_id`),
              KEY `tenant_id` (`tenant_id`,`status`,`position`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `category` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `parent_id` int(11) unsigned DEFAULT NULL,
              `lft` int(11) unsigned NOT NULL DEFAULT 0,
              `rgt` int(11) unsigned NOT NULL DEFAULT 0,
              `depth` int(11) unsigned NOT NULL DEFAULT 0,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `name` varchar(255) NOT NULL,
              `slug` varchar(100) NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `entry_count` int(11) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `slug` (`slug`),
              KEY `parent_id` (`parent_id`,`status`),
              KEY `category_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `entry_category` (
              `entry_id` int(11) unsigned NOT NULL,
              `category_id` int(11) unsigned NOT NULL,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              PRIMARY KEY (`entry_id`,`category_id`),
              KEY `entry_category_category_id_ibfk` (`category_id`),
              KEY `entry_category_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `block` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `name` varchar(250) NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `section_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `asset_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `entry_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              KEY `status` (`status`,`name`),
              KEY `block_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `section` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `entry_id` int(11) unsigned NOT NULL,
              `block_id` int(11) unsigned DEFAULT NULL,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `asset_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `entry_count` smallint(6) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              KEY `entry_id` (`entry_id`,`status`,`position`),
              KEY `section_updated_by_ibfk` (`updated_by_user_id`),
              KEY `section_block_id_ibfk` (`block_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `entry_relation` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `model_class` varchar(255) NOT NULL,
              `model_id` int(11) unsigned DEFAULT NULL,
              `entry_id` int(11) unsigned DEFAULT NULL,
              `position` smallint(6) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `model_class` (`model_class`,`model_id`,`entry_id`),
              KEY `entry_relation_entry_id_ibfk` (`entry_id`),
              KEY `entry_relation_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `cms_asset` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `entry_id` int(11) unsigned NOT NULL,
              `section_id` int(11) unsigned DEFAULT NULL,
              `file_id` int(11) unsigned NOT NULL,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `name` varchar(255) DEFAULT NULL,
              `content` text DEFAULT NULL,
              `alt_text` varchar(255) DEFAULT NULL,
              `link` varchar(255) DEFAULT NULL,
              `embed_url` text DEFAULT NULL,
              `hotspot_count` smallint(6) NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              PRIMARY KEY (`id`),
              KEY `entry_id` (`entry_id`,`status`,`position`),
              KEY `section_id` (`section_id`,`position`),
              KEY `cms_asset_file_id_ibfk` (`file_id`),
              KEY `cms_asset_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `permalink` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `tenant_id` int(11) unsigned NOT NULL,
              `entry_id` int(11) unsigned NOT NULL,
              `language` varchar(16) NOT NULL,
              `uri` varchar(255) NOT NULL,
              `slug` varchar(100) NOT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `uri` (`tenant_id`,`language`,`uri`),
              UNIQUE KEY `entry` (`entry_id`,`language`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD CONSTRAINT `entry_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `entry` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD CONSTRAINT `entry_tenant_id_ibfk` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry` ADD CONSTRAINT `entry_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `category` ADD CONSTRAINT `category_parent_id_ibfk` FOREIGN KEY (`parent_id`) REFERENCES `category` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `category` ADD CONSTRAINT `category_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry_category` ADD CONSTRAINT `entry_category_category_id_ibfk` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry_category` ADD CONSTRAINT `entry_category_entry_id_ibfk` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry_category` ADD CONSTRAINT `entry_category_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `block` ADD CONSTRAINT `block_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `section` ADD CONSTRAINT `section_block_id_ibfk` FOREIGN KEY (`block_id`) REFERENCES `block` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `section` ADD CONSTRAINT `section_entry_id_ibfk` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `section` ADD CONSTRAINT `section_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry_relation` ADD CONSTRAINT `entry_relation_entry_id_ibfk` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `entry_relation` ADD CONSTRAINT `entry_relation_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `cms_asset` ADD CONSTRAINT `cms_asset_entry_id_ibfk` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `cms_asset` ADD CONSTRAINT `cms_asset_file_id_ibfk` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `cms_asset` ADD CONSTRAINT `cms_asset_section_id_ibfk` FOREIGN KEY (`section_id`) REFERENCES `section` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `cms_asset` ADD CONSTRAINT `cms_asset_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `permalink` ADD CONSTRAINT `permalink_entry_id_ibfk` FOREIGN KEY (`entry_id`) REFERENCES `entry` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `permalink` ADD CONSTRAINT `permalink_tenant_id_ibfk` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE CASCADE
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
