<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alt text' => '',
    'Are you sure you want to remove this asset?' => '',
    'Assets' => '',
    'Content' => '',
    'Create New Entry' => '',
    'Create New Section' => '',
    'Create Section' => '',
    'Delete Entry' => '',
    'Edit Asset' => '',
    'Edit Entry' => '',
    'Entries' => '',
    'Entry' => '',
    'Library' => '',
    'Link' => '',
    'Meta description' => '',
    'Meta title' => '',
    'New Entry' => '',
    'New Section' => '',
    'Notice: Removing an asset will not delete the actual file.' => '',
    'Permanently delete related files' => '',
    'Published' => '',
    'Remove' => '',
    'Remove Asset' => '',
    'Sections' => '',
    'The asset was added.' => '',
    'The asset was created.' => '',
    'The asset was deleted.' => '',
    'The asset was updated.' => '',
    'The entry was created.' => '',
    'The entry was deleted.' => '',
    'The entry was updated.' => '',
    'The section was created.' => '',
    'The section was deleted.' => '',
    'The section was updated.' => '',
    'Title' => '',
    'Update Section' => '',
    'Upload' => '',
    'Url' => '',
    'View All Entries' => '',
    'View All Sections' => '',
    'Warning: Deleting this entry cannot be undone. All related sections will also be unrecoverably deleted. Please be certain!' => '',
    'Warning: Deleting this file cannot be undone. All related assets will also be unrecoverably deleted. Please be certain!' => '',
    '[ No title ]' => '',
];
